version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfiles/vuejs
    depends_on:
      -  drf
    ports:
      - "${FRONTEND_PORT}:8080"
    volumes:
      - ./src/frontend:/opt/frontend
      - /opt/frontend/node_modules
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - CHOKIDAR_USEPOLLING=true
      - API_HOST=drf
      - API_PORT=${DRF_PORT}
  drf:
    build:
      context: .
      dockerfile: dockerfiles/drf
    depends_on:
      - db
    ports:
      - "${DRF_PORT}:8000"
    volumes:
      - ./src/api:/opt/api
  db:
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret

volumes:
  pgdata:
