version: '3'

services:
  frontend:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: dockerfiles/vuejs
    entrypoint: /entrypoint.sh
    depends_on:
      -  drf
    ports:
      - "${FRONTEND_PORT}:8080"
    volumes:
      - ./src/frontend:/opt/frontend
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - CHOKIDAR_USEPOLLING=true
      - API_HOST=${DRF_RUNNING_ON_HOST}
      - API_PORT=${DRF_RUNNING_ON_PORT}
  drf:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: dockerfiles/drf
    depends_on:
      - db
    ports:
      - "${DRF_PORT}:8000"
    volumes:
      - ./src/api:/opt/api
    environment:
      - PYTHONPATH=/opt/api
      - DJANGO_SETTINGS_MODULE=api.settings
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret

volumes:
  pgdata:
